### ISSUE TITLE
JDEE server can't be built in JDK9.

### ISSUE THREAD

**Issue by Ailrun** [jdee-emacs/jdee#133]
When I execute `mvn -Dmaven.test.skip=true assembly:assembly` with environment using JDK9, it cause following error.

```
java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:86)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
...
```

After my short search, I found [this](https://issues.apache.org/jira/browse/MASSEMBLY-834) issue which looks related with this problem.
Is the problem with the version of dependencies of JDEE server, or just my fault?

**Comment by pwojnowski** [comment]
I've updated the assembly plugin. Please try again now, but just ```mvn -Dmaven.test.skip=true package``` as building bundle is now attached to the package phase.

The link to the issue helped a lot. Thank you! :+1:

**Comment by Ailrun** [comment]
@pwojnowski 
It's buildable, but after build it, following errors occur.

```
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size") [20 times]
Variable binding depth exceeds max-specpdl-size
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size")
Variable binding depth exceeds max-specpdl-size [2 times]
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size") [2 times]
Variable binding depth exceeds max-specpdl-size
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size")
Variable binding depth exceeds max-specpdl-size [3 times]
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size") [3 times]
Variable binding depth exceeds max-specpdl-size
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size")
Variable binding depth exceeds max-specpdl-size [2 times]
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size") [2 times]
Variable binding depth exceeds max-specpdl-size
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c-known-type-key’: (error "Variable binding depth exceeds max-specpdl-size")
Variable binding depth exceeds max-specpdl-size [3 times]
Args out of range: #<buffer java version>, 0, 0
```

and repeated.

**Comment by Ailrun** [comment]
Maybe related with https://github.com/jdee-emacs/jdee/issues/114?

**Comment by pwojnowski** [comment]
JDK 9 support is not there yet, but this seems to be a different problem. Please try this suggestion to track down the problem: https://stackoverflow.com/questions/1322591/tracking-down-max-specpdl-size-errors-in-emacs

**Comment by Ailrun** [comment]
@pwojnowski 
1. It looks #<buffer java version>, 0, 0` is the only issue related with jdee.
https://github.com/jdee-emacs/jdee/blob/4d3ed730a187b6e82a6ee8dffaf4c29a9a3986af/jdee-jdk-manager.el#L33
    - This function can't detect Java version 9, since `java -version` prints following, so there's no `\"1.9\"` and only `\"9\"`.
```
java version \"9\"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

2. I can't print the stack trace after following your link....
What I do is
```
(setq max-specpdl-size 5)
(setq debug-on-error t)
(jdee-mode)
```
and it prints just the same....
If it's not border you, could you help me little bit?

**Comment by pwojnowski** [comment]
I've updated the regexp to work also with version reported by Java 9.
JDK 9 changes also required changes to JDEE Server, so please rebuild it too.
I'm closing this issue as it's original problem is solved. Please put other problems in separate issues. Thank you!

**Comment by Ailrun** [comment]
@pwojnowski Thx for your hard work!
