### ISSUE TITLE
checkstyle supported halfways

### ISSUE THREAD

**Issue by Reissner** [jdee-emacs/jdee#58]
Still jdee-checkstyle.el is present but trying yields: 

/usr/lib64/jvm/javaLatest/bin/java -classpath /home/ernst/.emacs.d/jdee-master/java/lib/checkstyle-all.jar com.puppycrawl.tools.checkstyle.Main -c /home/ernst/.emacs.d/jdee-master/java/lib/sun_checks.xml Actions.java

Error: Could not find or load main class com.puppycrawl.tools.checkstyle.Main

Well, the jar is missing. 

Do you plan to give up support for checkstyle or just forgotten to add the jar? 
I found, you removed the lib-folder with all jars in it. 

Compilation exited abnormally with code 1 at Fri Jun  3 19:57:52

**Comment by oldButNotWise** [comment]
You need to get your own copy of Checkstyle (and other required libs). Once you do, you can tell JDEE where to find it by using something like this
```
(setq jdee-checkstyle-classpath 
      (mapcar (lambda (lib) (expand-file-name (concat "lib/checkstyle/" lib ".jar") user-emacs-directory))
              '("checkstyle-6.0" "antlr-2.7.7" "guava-18.0"
                "commons-beanutils-1.8.3" "commons-logging-1.2" "commons-cli-1.2"))
      ;; Default checkstyle rules; can be overridden per project
      jdee-checkstyle-style
      (expand-file-name "etc/checkstyle.xml" user-emacs-directory))
```

**Comment by LeeiFrankJaw** [comment]
After I spent some time putting the right jar and xml into the right place and click `Check Style` from `JDEE` submenu within Emacs, I got the following error.

    Starting audit...
    com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C02E02_GridLines.java
    	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
    	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
    	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
    	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
    	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
    Caused by: java.lang.NullPointerException
    	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
    	at java.util.concurrent.ConcurrentHashMap$KeySetView.add(ConcurrentHashMap.java:4595)
    	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocPackageCheck.processFiltered(JavadocPackageCheck.java:73)
    	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
    	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
    	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
    	... 4 more
    Checkstyle ends with 1 errors.

So I tried to execute checkstyle directly from terminal, I got the expected output.

    $ java -cp ~/.emacs.d/elpa/jdee-2.4.2/java/lib/checkstyle-all.jar com.puppycrawl.tools.checkstyle.Main -c ~/.emacs.d/elpa/jdee-2.4.2/java/lib/sun_checks.xml src/main/java/tutorial/chapter02/C02E02_GridLines.java 
    Starting audit...
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:0: Missing package-info.java file. [JavadocPackage]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:22:14: Name 'C02E02_GridLines' must match pattern '^[A-Z][a-zA-Z0-9]*$'. [TypeName]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:24:5: Missing a Javadoc comment. [JavadocVariable]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:26:5: Missing a Javadoc comment. [JavadocMethod]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:26:29: Parameter args should be final. [FinalParameters]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:26:40: Array brackets at illegal position. [ArrayTypeStyle]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:32:5: Class 'C02E02_GridLines' looks like designed for extension (can be subclassed), but the method 'createPdf' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'C02E02_GridLines' final or making the method 'createPdf' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:32:5: Missing a Javadoc comment. [JavadocMethod]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:32:27: Parameter dest should be final. [FinalParameters]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:44:57: '0.875f' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:45:58: '0.176f' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:46:47: '0.156f' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:46:60: '0.118f' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:48:29: '0.5f' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:51: Line is longer than 80 characters (found 102). [LineLength]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:51:51: '57' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:51:88: '56' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:51:98: '40' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:52:49: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:53:49: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:56: Line is longer than 80 characters (found 100). [LineLength]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:56:50: '61' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:56:86: '60' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:56:96: '40' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:57:53: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:58:53: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:63:29: '3' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:68:30: '10' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:68:34: '10' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:69:47: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:69:75: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:70: Line is longer than 80 characters (found 82). [LineLength]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:70:45: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:70:70: '15' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:73:21: '20' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:74:22: '22.5' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:74:28: '7.5' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:74:33: '30' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:74:37: '10' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:75:22: '37.5' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:75:28: '12.5' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:75:34: '40' is a magic number. [MagicNumber]
    [ERROR] /home/leiz/Portfolio/Java/iText7-jump-start/Chapter2/src/main/java/tutorial/chapter02/C02E02_GridLines.java:75:38: '20' is a magic number. [MagicNumber]
    Audit done.
    Checkstyle ends with 43 errors.

I wonder if it's a jdee bug due to different execution environment and why I got different output. After I spent some time investigating the cause, I found out this is a bug in checkstyle.

The same output can be reproduced from terminal by cd to the source file directory and execute checkstyle there.

    $ cd src/main/java/tutorial/chapter02/
    
    $ java -cp ~/.emacs.d/elpa/jdee-2.4.2/java/lib/checkstyle-all.jar com.puppycrawl.tools.checkstyle.Main -c ~/.emacs.d/elpa/jdee-2.4.2/java/lib/sun_checks.xml C02E02_GridLines.java 
    Starting audit...
    com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C02E02_GridLines.java
    	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
    	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
    	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
    	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
    	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
    Caused by: java.lang.NullPointerException
    	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
    	at java.util.concurrent.ConcurrentHashMap$KeySetView.add(ConcurrentHashMap.java:4595)
    	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocPackageCheck.processFiltered(JavadocPackageCheck.java:73)
    	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
    	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
    	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
    	... 4 more
    Checkstyle ends with 1 errors.

My checkstyle version is 8.2 and I haven't check it out whether old versions have the same problem.
